version: '3'
services:

  #nginx
  web:
    image: nginx/alpine
    container_name: nginx
    ports:
      - '8025:80'
    volumes:
      # - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  #MySQL
  db:
    image: mysql
    container_name: mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: secreto

  #PHPMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - "3401:80"
    depends_on:
      - db

  #Laravel Image
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
      # - .:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
